AgendamentoProjeto/Controllers/AvisosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendamentoProjeto.Models;
using Microsoft.AspNetCore.Http;

namespace AgendamentoProjeto.Controllers
{
    public class AvisosController : Controller
    {
        private readonly Contexto _context;

        public AvisosController(Contexto context)
        {
            _context = context;
        }

        // GET: Avisos
        public async Task<IActionResult> Index()
        {

            var agendamentos = _context.Agendamento.Select(a => a).Include(a=>a.Professor).Include(a=>a.Usuario).ToList();
            ViewBag.Agendamentos = agendamentos;
            var avisosParaApagar = _context.Aviso.Select(a => a).ToList();
            foreach(var xom in avisosParaApagar)
            {
             foreach(var xim in agendamentos)
                {
                    if (xim.DataFimAgendamento.Date < DateTime.Now.Date)
                    {
                        if (xim.AgendamentoId == xom.AgendamentoId)
                        {
                            _context.Aviso.Remove(xom);
                            await _context.SaveChangesAsync();
                        }
                    }
                }
            }
            return View(await _context.Aviso.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string Procurar)
        {
            if (!String.IsNullOrEmpty(Procurar))
            {

                return View(await _context.Aviso.Where(x => x.Mensagem.ToUpper().Contains(Procurar.ToUpper())).ToListAsync());
            }

            return View(await _context.Aviso.ToListAsync());
        }

        // GET: Avisos/Create
        public IActionResult Create(int AgendamentoId)
        {
            ViewData["agendamentoId"] = AgendamentoId;
            return View();
        }

        // POST: Avisos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Criar([Bind("AgendamentoId,AvisosId,Mensagem")] Aviso aviso)
        {


            //var ids = _context.Aviso.Count() + 1;
            //aviso.AvisosId = ids;
            if (aviso != null)
            {
                _context.Add(aviso);
                await _context.SaveChangesAsync();

                if (HttpContext.Session.GetString("Cargo") == "Coordenador")
                {
                    return RedirectToAction("MeusAgendamentos", "Agendamentos");
                }
                else
                {
                    return RedirectToAction("Index", "Agendamentos");

                }
            }

            // ViewData["agendamentoId"] = aviso.AgendamentoId;
            return View("Create", aviso);
        }


        // GET: Avisos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aviso = await _context.Aviso.FindAsync(id);
            if (aviso == null)
            {
                return NotFound();
            }
            ViewBag.agendamentoId = aviso.AgendamentoId;
            ViewData["AvisosId"] = new SelectList(_context.Agendamento, "AgendamentoId", "AgendamentoId", aviso.AvisosId);
            return View(aviso);
        }

        // POST: Avisos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AvisosId,AgendamentoId,Mensagem")] Aviso aviso)
        {
            if (id != aviso.AvisosId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aviso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvisoExists(aviso.AvisosId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AvisosId"] = new SelectList(_context.Agendamento, "AgendamentoId", "AgendamentoId", aviso.AvisosId);
            return View(aviso);
        }

       
        // POST: Avisos/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var aviso = await _context.Aviso.FindAsync(id);
            _context.Aviso.Remove(aviso);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AvisoExists(int id)
        {
            return _context.Aviso.Any(e => e.AvisosId == id);
        }
    }
}

AgendamentoProjeto/Controllers/CargosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendamentoProjeto.Models;

namespace AgendamentoProjeto.Controllers
{
    public class CargosController : Controller
    {
        private readonly Contexto _context;

        public CargosController(Contexto context)
        {
            _context = context;
        }

        // GET: Cargos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cargos.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string Procurar)
        {
            if (!String.IsNullOrEmpty(Procurar))
            {
               
                return View(await _context.Cargos.Where(x => x.NomeCargo.ToUpper().Contains(Procurar.ToUpper())).ToListAsync());
            }
          
            return View(await _context.Cargos.ToListAsync());
        }

        // GET: Cargos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargos
                .FirstOrDefaultAsync(m => m.CargoId == id);
            if (cargo == null)
            {
                return NotFound();
            }

            return View(cargo);
        }

        // GET: Cargos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cargos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CargoId,NomeCargo")] Cargo cargo)
        {
            var temCargo = _context.Cargos.Where(x => x.NomeCargo == cargo.NomeCargo).ToList();
            if (temCargo.Count > 0)
            {
                ViewBag.TemCargo = true;
                return View();
            }
            if (ModelState.IsValid)
            {
                _context.Add(cargo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cargo);
        }

        // GET: Cargos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargos.FindAsync(id);
            if (cargo == null)
            {
                return NotFound();
            }
            return View(cargo);
        }

        // POST: Cargos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CargoId,NomeCargo")] Cargo cargo)
        {
            if (id != cargo.CargoId)
            {
                return NotFound();
            }

            var temCargo = _context.Cargos.Where(x => x.NomeCargo == cargo.NomeCargo && x.CargoId != cargo.CargoId).ToList();
            if (temCargo.Count > 0)
            {
                ViewBag.TemCargo = true;
                return View();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cargo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CargoExists(cargo.CargoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cargo);
        }


        // POST: Cargos/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var cargo = await _context.Cargos.FindAsync(id);
            _context.Cargos.Remove(cargo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CargoExists(int id)
        {
            return _context.Cargos.Any(e => e.CargoId == id);
        }
    }
}

AgendamentoProjeto/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AgendamentoProjeto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MailKit.Net.Smtp;
using MimeKit;
using Microsoft.AspNetCore.Http;

namespace AgendamentoProjeto.Controllers
{
    public class LoginController : Controller
    {
        private readonly Contexto _contexto;
        int CodigoGeral;
        public LoginController(Contexto contexto)
        {
            _contexto = contexto;
        }
        public IActionResult Index()
        {
            //bool logado = true;
            //if (logado)
            //{
            //    return RedirectToAction("Index","Agendamentos");
            //}
            //else
            //{
            //    return RedirectToAction("Logar");
            //}
            return RedirectToAction("Logar");
        }

        public IActionResult Logar()
        {
            ViewData["CargoId"] = new SelectList(_contexto.Cargos, "CargoId", "NomeCargo");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Logar([Bind("UsuarioId,Login,Senha,CargoId,StatusId")] Usuario usuario)
        {
            ViewData["CargoId"] = new SelectList(_contexto.Cargos, "CargoId", "NomeCargo");
            //var login = from user in _contexto.Usuarios where user.Login == usuario.Login && user.Senha == usuario.Senha && user.CargoId == usuario.CargoId && usuario.StatusId == 1 select user;
            var login = _contexto.Usuarios.Where(u => u.Login == usuario.Login && u.Senha == usuario.Senha && u.CargoId == usuario.CargoId && u.StatusId == 1).Include(u=>u.Cargo).ToList();
     
            if (login.Any())
            {
                var x = login.Select(a=>a.UsuarioId).FirstOrDefault();
                var y = login.Select(a => a.Email).FirstOrDefault();
                var z = login.Select(a => a.Cargo.NomeCargo).FirstOrDefault();
                HttpContext.Session.SetInt32("usuarioIdLogado", x);
                HttpContext.Session.SetString("LoginLogado", usuario.Login);
                HttpContext.Session.SetString("EmailLogado", y);
                HttpContext.Session.SetString("Cargo", z);
                if (z == "T.I")
                {
                    return RedirectToAction("Index", "Agendamentos");
                }
                else
                {
                    return RedirectToAction("MeusAgendamentos", "Agendamentos");
                }
                
            }
            else
            {
                TempData["msgSucesso"] = "Login, senha ou cargo incorretos ou usuário inativo.";
                return View("Logar");
            }


        }

        public IActionResult GerarSenha()
        {
            ViewData["CargoId"] = new SelectList(_contexto.Cargos, "CargoId", "NomeCargo");
            ViewData["CursoId"] = new SelectList(_contexto.Cursos, "CursoId", "Nome");
            return View();
        }

        public IActionResult EsqueciSenha(bool naoResetou, string erroCode)
        {
            if (erroCode == "sim")
            {
                ViewBag.erroCode = true;
            }
            if (naoResetou == true)
            {
                ViewBag.naoResetou = true;
            }
            return View();
        }

        public IActionResult ValidarCodigo(string Login, string Senha, int codigo)
        {
            int c = Convert.ToInt32(HttpContext.Session.GetInt32("code"));
            if (c == codigo)
            {
                Usuario user = _contexto.Usuarios.Where(x => x.Login == Login).FirstOrDefault();
                user.Senha = Senha;
                _contexto.Update(user);
                 _contexto.SaveChanges();
                return View();
            }
            else
            {
                return RedirectToAction("EsqueciSenha", new { naoResetou = true });

            }
        }

        public IActionResult GerarCodigo(string Login, string Email)
        {
            var SucessoDados = _contexto.Usuarios.Where(x => x.Login == Login && x.Email == Email).ToList();
            if (SucessoDados.Count >0)
            {
                MimeMessage message = new MimeMessage();

                MailboxAddress from = new MailboxAddress("Admin",
                "projetoprofi2019@gmail.com");
                message.From.Add(from);

                MailboxAddress to = new MailboxAddress("Usuário",
                Email);
                message.To.Add(to);

                message.Subject = "Reset de senha";
                Random randNum = new Random();
                CodigoGeral = randNum.Next(100) + randNum.Next(100) + randNum.Next(100) + randNum.Next(100) + randNum.Next(100);
                HttpContext.Session.SetInt32("code", CodigoGeral);
                BodyBuilder bodyBuilder = new BodyBuilder();
                bodyBuilder.HtmlBody = $"<p>Olá querido usuário, segue seu código de reset de senha {CodigoGeral} <p>";
                bodyBuilder.TextBody = "Reset de senha";
                message.Body = bodyBuilder.ToMessageBody();
                SmtpClient client = new SmtpClient();
                client.Connect("smtp.gmail.com", 465, true);
                client.Authenticate("projetoprofi2019@gmail.com", "projetoMERDA123");
                client.Send(message);
                client.Disconnect(true);
                client.Dispose();
                return View("GerarCodigo");

            }
            else
            {

                return RedirectToAction("EsqueciSenha", new {naoResetou = false, erroCode = "sim" });
            }
          
        }

        public IActionResult Sair()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Logar");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EnviarSolic([Bind("UsuarioId,Login,Senha,Email,CursoId,NomeUsuario,CargoId")] Usuario usuario)
        {
            try
            {
                int IdBanco = 0;
                var stats = _contexto.Status.Where(x => x.NomeStatus == "pendente").FirstOrDefault();
                var emailRepetido = _contexto.Usuarios.Select(u => u.Email).Contains(usuario.Email);
                var loginRepetido = _contexto.Usuarios.Select(u => u.Login).Contains(usuario.Login);
                IdBanco = stats.StatusId;
                var idUser = _contexto.Usuarios.Count() + 1;
                if (emailRepetido == true)
                {
                    TempData["msgSucesso"] = "E-mail já consta em nossa base de dados, favor insira outro e-mail";
                    return RedirectToAction("GerarSenha");
                }
                if (loginRepetido == true)
                {
                    TempData["msgSucesso"] = "Login já consta em nossa base de dados, favor insira outro Login";
                    return RedirectToAction("GerarSenha");
                }

                usuario.StatusId = 2;
                _contexto.Add(usuario);
                TempData["msgSucesso"] = "Solicitação enviada com sucesso";
                await _contexto.SaveChangesAsync();

                return RedirectToAction("Logar");
            }
            catch
            {
                TempData["msgSucesso"] = "Ocorreu um erro na sua solicitação, favor contate o administrador do site";
                return RedirectToAction("GerarSenha");
            }
        }
    }
}

AgendamentoProjeto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]AgendamentoProjeto</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />


    <link rel="stylesheet" href="~/font-awesome/css/brands.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/regular.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/solid.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/svg-with-js.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/v4-shims.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/cursos.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand font-italic" href="#">Agendamentos UCB</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                <ul class="navbar-nav mr-auto ml-5">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Agendamentos" asp-action="Index">Agendamentos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Agendamentos" asp-action="DashBoardAgendamentos">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Professors" asp-action="Index">Professores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Avisos" asp-action="Index">Avisos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Cargos" asp-action="Index">Cargos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Disciplinas" asp-action="Index">Disciplinas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Laboratorios" asp-action="Index">Laboratórios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
                    </li>
                </ul>

            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex">
            &copy; Sistema de agendamentos UCB.
            <p class="ml-5">Equipe:</p>
            <ul class="d-flex ">
                <li>Jonathan Oliveira</li>
                <li class="ml-5">Rodrigo Lima</li>
                <li class="ml-5">Thiago Moura</li>
            </ul>
        </div>
    </footer>




    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/font-awesome/js/all.min.js"></script>
    <script src="~/font-awesome/js/brands.min.js"></script>
    <script src="~/font-awesome/js/conflict-detection.min.js"></script>
    <script src="~/font-awesome/js/fontawesome.min.js"></script>
    <script src="~/font-awesome/js/regular.min.js"></script>
    <script src="~/font-awesome/js/solid.min.js"></script>
    <script src="~/font-awesome/js/v4-shims.min.js"></script>
    <script src="~/datepicker/datepicker.min.js"></script>
    <script src="~/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/moment.js/moment.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AgendamentoProjeto/Views/Shared/_LayoutCoordenador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]AgendamentoProjeto</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />


    <link rel="stylesheet" href="~/font-awesome/css/brands.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/regular.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/solid.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/svg-with-js.min.css" />
    <link rel="stylesheet" href="~/font-awesome/css/v4-shims.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/cursos.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand font-italic" href="#">Agendamentos UCB</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
                <ul class="navbar-nav mr-auto ml-5">
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Agendamentos" asp-action="SolicitarAgendamento">Solicitar Agendamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Agendamentos" asp-action="MeusAgendamentos">Meus Agendamentos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Agendamentos" asp-action="DashBoardAgendamentos">Dashboard de Agendamentos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a>
                    </li>
                  
                </ul>

            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex">
            &copy; Projeto profissional 2019.
            <p class="ml-5">Equipe:</p>
            <ul class="d-flex ">
                <li>Jonathan Oliveira</li>
                <li class="ml-5">Rodrigo Lima</li>
                <li class="ml-5">Thiago Moura</li>
            </ul>
        </div>
    </footer>




    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/font-awesome/js/all.min.js"></script>
    <script src="~/font-awesome/js/brands.min.js"></script>
    <script src="~/font-awesome/js/conflict-detection.min.js"></script>
    <script src="~/font-awesome/js/fontawesome.min.js"></script>
    <script src="~/font-awesome/js/regular.min.js"></script>
    <script src="~/font-awesome/js/solid.min.js"></script>
    <script src="~/font-awesome/js/v4-shims.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

AgendamentoProjeto/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendamentoProjeto</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/login.css" />
</head>
<body>
   
    <div class="container">
       
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>