AgendamentoProjeto/Models/Laboratorio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AgendamentoProjeto.Models
{
    [Table("AGV_Laboratorio")]
    public class Laboratorio
    {
        [Key]
        public int LaboratorioId { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(30, ErrorMessage = "Limite de caracteres atingido")]
        [Display(Name = "Nome do Laboratório")]
        public string NomeLaboratorio { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(150, ErrorMessage = "Limite de caracteres atingido")]
        [Display(Name = "Descrição de hardware")]
        public string Hardware { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [StringLength(150, ErrorMessage = "Limite de caracteres atingido")]
        [Display(Name = "Descrição de software")]
        public string Software { get; set; }
        [Required(ErrorMessage = "Campo obrigatório")]
        [Display(Name = "Quantidade de computadores")]
        public int QuantidadePcs { get; set; }
        [Display(Name = "Tem projetor?")]
        public bool Projetor { get; set; }
        public int? StatusId { get; set; }
        public Status Status { get; set; }

        public ICollection<Agendamento> Agendamentos { get; set; }
    }
}

AgendamentoProjeto/Controllers/LaboratoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgendamentoProjeto.Models;

namespace AgendamentoProjeto.Controllers
{
    public class LaboratoriosController : Controller
    {
        private readonly Contexto _context;

        public LaboratoriosController(Contexto context)
        {
            _context = context;
        }

        // GET: Laboratorios
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Laboratorio.Include(l => l.Status);


            ViewBag.statusBd = _context.Status.Select(s => s.NomeStatus);
            ViewBag.quantidades = _context.Laboratorio.Select(l => l.QuantidadePcs);
            return View(await contexto.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string Procurar)
        {
            if (!String.IsNullOrEmpty(Procurar))
            {
                ViewBag.statusBd = _context.Status.Select(s => s.NomeStatus);
                ViewBag.quantidades = _context.Laboratorio.Select(l => l.QuantidadePcs);
                return View(await _context.Laboratorio.Where(x => x.NomeLaboratorio.ToUpper().Contains(Procurar.ToUpper())).ToListAsync());
            }
            ViewBag.statusBd = _context.Status.Select(s => s.NomeStatus);
            ViewBag.quantidades = _context.Laboratorio.Select(l => l.QuantidadePcs);
            return View(await _context.Laboratorio.ToListAsync());
        }


        // GET: Laboratorios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laboratorio = await _context.Laboratorio
                .Include(l => l.Status)
                .FirstOrDefaultAsync(m => m.LaboratorioId == id);
            if (laboratorio == null)
            {
                return NotFound();
            }

            return View(laboratorio);
        }

        public async Task<IActionResult> Manutencao(int id)
        {
            var lab = _context.Laboratorio.Where(l => l.LaboratorioId == id).FirstOrDefault();
            try
            {

                lab.StatusId = 5;
                _context.Update(lab);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LaboratorioExists(lab.LaboratorioId))
                {
                    return NotFound();
                }
                else
                {
                    return View("Index");
                }
            }
        }

        // GET: Laboratorios/Create
        public IActionResult Create()
        {
            ViewData["LaboratorioId"] = new SelectList(_context.Status, "StatusId", "NomeStatus");
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "NomeStatus");
            return View();
        }

        // POST: Laboratorios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LaboratorioId,NomeLaboratorio,Hardware,Software,QuantidadePcs,Projetor,StatusId")] Laboratorio laboratorio)
        {

            var temLaboratorio = _context.Laboratorio.Where(l => l.NomeLaboratorio == laboratorio.NomeLaboratorio).ToList();
            if (temLaboratorio.Any())
            {
                ViewBag.error = "Nome do laboratório já consta no banco de dados.";
                ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "NomeStatus");
                return View();
            }
            if (ModelState.IsValid)
            {
                _context.Add(laboratorio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LaboratorioId"] = new SelectList(_context.Status, "StatusId", "NomeStatus", laboratorio.LaboratorioId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "NomeStatus");
            return View(laboratorio);
        }

        // GET: Laboratorios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var laboratorio = await _context.Laboratorio.FindAsync(id);
            if (laboratorio == null)
            {
                return NotFound();
            }
            ViewData["LaboratorioId"] = new SelectList(_context.Status, "StatusId", "NomeStatus", laboratorio.LaboratorioId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "NomeStatus");

            return View(laboratorio);
        }

        // POST: Laboratorios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LaboratorioId,NomeLaboratorio,Hardware,Software,QuantidadePcs,Projetor,StatusId")] Laboratorio laboratorio)
        {
            if (id != laboratorio.LaboratorioId)
            {
                return NotFound();
            }

            var temLaboratorio = _context.Laboratorio.Where(l => l.NomeLaboratorio == laboratorio.NomeLaboratorio && l.LaboratorioId != laboratorio.LaboratorioId).ToList();
            if (temLaboratorio.Any())
            {
                ViewBag.error = "Nome do laboratório já consta no banco de dados.";
                ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "NomeStatus");
                return View("Edit");
            }

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(laboratorio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LaboratorioExists(laboratorio.LaboratorioId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LaboratorioId"] = new SelectList(_context.Status, "StatusId", "NomeStatus", laboratorio.LaboratorioId);
            return View(laboratorio);
        }

        

        // POST: Laboratorios/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var laboratorio = await _context.Laboratorio.FindAsync(id);
            _context.Laboratorio.Remove(laboratorio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LaboratorioExists(int id)
        {
            return _context.Laboratorio.Any(e => e.LaboratorioId == id);
        }
    }
}

AgendamentoProjeto/Views/Laboratorios/Create.cshtml
@model AgendamentoProjeto.Models.Laboratorio
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Index";
    if (HttpContextAccessor.HttpContext.Session.GetString("Cargo") == "T.I")
    {
        Layout = "_Layout";
    }
    else
    {
        Layout = "_LayoutCoordenador";
    }
}
@if (ViewBag.error != null)
{
    <div class="alert alert-danger mt-2" style="height:45px;">
        <p><strong>@ViewBag.error</strong></p>
    </div>
}

<h4 class="mt-4 text-primary">Adicionar Laboratório</h4>
<hr />

<div class="row">
    <div class="col-md-3">

    </div>
    <div class="border border-primary rounded bg-light pt-xl-5 pb-xl-5 col-md-5 ml-3" style="padding-left:100px;padding-right:100px;">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="NomeLaboratorio" class="control-label"></label>
                <input asp-for="NomeLaboratorio" class="form-control" />
                <span asp-validation-for="NomeLaboratorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hardware" class="control-label"></label>
                <input asp-for="Hardware" class="form-control" />
                <span asp-validation-for="Hardware" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Software" class="control-label"></label>
                <input asp-for="Software" class="form-control" />
                <span asp-validation-for="Software" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="QuantidadePcs" class="control-label"></label>
                <input asp-for="QuantidadePcs" class="form-control" />
                <span asp-validation-for="QuantidadePcs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Projetor" /> @Html.DisplayNameFor(model => model.Projetor)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-success" />
                <a asp-action="Index" class="btn ml-2 btn-info text-white">Voltar</a>
            </div>
        </form>
    </div>
    <div class="col-md-3">

    </div>

</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AgendamentoProjeto/Views/Laboratorios/Delete.cshtml
@model AgendamentoProjeto.Models.Laboratorio

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Laboratorio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeLaboratorio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeLaboratorio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hardware)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hardware)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Software)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Software)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantidadePcs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantidadePcs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Projetor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Projetor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.NomeStatus)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LaboratorioId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AgendamentoProjeto/Views/Laboratorios/Details.cshtml
@model AgendamentoProjeto.Models.Laboratorio

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Laboratorio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeLaboratorio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeLaboratorio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hardware)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hardware)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Software)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Software)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantidadePcs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantidadePcs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Projetor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Projetor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.NomeStatus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LaboratorioId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AgendamentoProjeto/Views/Laboratorios/Edit.cshtml
@model AgendamentoProjeto.Models.Laboratorio
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Index";
    if (HttpContextAccessor.HttpContext.Session.GetString("Cargo") == "T.I")
    {
        Layout = "_Layout";
    }
    else
    {
        Layout = "_LayoutCoordenador";
    }
}

@if (ViewBag.error != null)
{
    <div class="alert alert-danger mt-2" style="height:45px;">
        <p><strong>@ViewBag.error</strong></p>
    </div>
}

<h4 class="mt-4 text-primary">Atualizar Laboratório</h4>
<hr />
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="border border-primary rounded bg-light pt-xl-5 pb-xl-5 col-md-5 ml-3" style="padding-left:100px;padding-right:100px;">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LaboratorioId" />
            <div class="form-group">
                <label asp-for="NomeLaboratorio" class="control-label"></label>
                <input asp-for="NomeLaboratorio" class="form-control" />
                <span asp-validation-for="NomeLaboratorio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hardware" class="control-label"></label>
                <input asp-for="Hardware" class="form-control" />
                <span asp-validation-for="Hardware" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Software" class="control-label"></label>
                <input asp-for="Software" class="form-control" />
                <span asp-validation-for="Software" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="QuantidadePcs" class="control-label"></label>
                <input asp-for="QuantidadePcs" class="form-control" />
                <span asp-validation-for="QuantidadePcs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="StatusId" class="form-control" asp-items="ViewBag.StatusId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Projetor" /> @Html.DisplayNameFor(model => model.Projetor)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success" />
                <a asp-action="Index" class="btn ml-2 btn-info text-white">Voltar</a>
            </div>
        </form>
    </div>
    <div class="col-md-3">

    </div>

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AgendamentoProjeto/Views/Laboratorios/Index.cshtml
@model IEnumerable<AgendamentoProjeto.Models.Laboratorio>
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using Microsoft.AspNetCore.Http
@{
    ViewData["Title"] = "Index";
    if (HttpContextAccessor.HttpContext.Session.GetString("Cargo") == "T.I")
    {
        Layout = "_Layout";
    }
    else
    {
        Layout = "_LayoutCoordenador";
    }
}

<h1 style="text-align:center;font-weight:bold;font-size:30px;" class="mt-3 text-primary">Laboratórios</h1>
<br />
<br />
<ul class="navbar-nav  flex-row mt-4">


    <li class="nav-item">

        <form asp-action="Index" method="post">
            <div class="input-group">
                <input class="form-control py-2" type="search" name="Procurar" placeholder="Pesquisar por nome..." id="example-search-input">
                <span class="input-group-append">
                    <button class="btn btn-outline-info" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
    </li>


    <li>
        <div class="ml-2">
            <a asp-action="Create" class="text-white btn btn-success"> <i class="fa fa-plus fa-1x"></i> </a>
        </div>
    </li>



</ul>

<div class="container mt-3">
    <div class="row" style="align-items:center;">
        @foreach (var item in Model)
        {

            <div class="col-md-4 mt-3 ">
                <div class="card bg-light">
                    <div class="card-body border rounded border-primary">
                        <div class="d-flex">
                            <div class="d-flex">
                                <label class="fonteSquares">Computadores: </label>
                                <label class="fonteSquares text-primary ml-2 font-weight-bold">@Html.DisplayFor(modelItem => item.QuantidadePcs)</label>
                            </div>
                            @if (item.StatusId == 1)
                            {
                                <span style="height:20px;margin-left:60px;" class="badge badge-success">Disponível</span>
                            }
                            else if (item.StatusId == 2)
                            {
                                <span style="height:20px;margin-left:60px;" class="badge badge-warning">Pendente</span>
                            }
                            else if (item.StatusId == 3)
                            {
                                <span style="height:20px;margin-left:60px;" class="badge badge-danger">Cancelado</span>
                            }
                            else if (item.StatusId == 4)
                            {
                                <span style="height:20px;margin-left:60px;" class="badge badge-dark">Bloqueado</span>
                            }
                            else if (item.StatusId == 5)
                            {
                                <span style="height:20px;margin-left:60px;" class="badge badge-info">Manutenção</span>
                            }
                        </div>
                        <div class="d-flex">
                            <label class="fonteSquares">Nome Laboratório: </label>
                            <label class="fonteSquares text-primary ml-2 font-weight-bold">@Html.DisplayFor(modelItem => item.NomeLaboratorio)</label>
                        </div>
                        <div class="d-flex">
                            <label class="fonteSquares">Hardware: </label>
                            <label class="fonteSquares text-primary ml-2 font-weight-bold">@Html.DisplayFor(modelItem => item.Hardware)</label>
                        </div>
                        <div class="d-flex">
                            <label class="fonteSquares">Software: </label>
                            <label class="fonteSquares text-primary ml-2 font-weight-bold">@Html.DisplayFor(modelItem => item.Software)</label>
                        </div>
                        <div class="d-flex">
                            <label class="fonteSquares">Tem projetor?: </label>
                            @if (item.Projetor == true)
                            {
                                <label class="fonteSquares text-primary ml-2 font-weight-bold">Sim</label>
                            }
                            else
                            {
                                <label class="fonteSquares text-primary ml-2 font-weight-bold">Não</label>
                            }

                        </div>
                        <div class="d-flex mt-3">
                            <a asp-action="Edit" asp-route-id="@item.LaboratorioId" class="btn ml-4 btn-sm btn-warning  font-weight-bold">Editar</a>
                            <a class="btn btn-sm btn-danger ml-4 text-white font-weight-bold" href="#" onclick="ExibirModal(@item.LaboratorioId)">Excluir</a>
                            <a href="@Url.Action("Manutencao", "Laboratorios", new { id = item.LaboratorioId })" class="btn ml-4 btn-sm btn-success text-white font-weight-bold">Manutenção</a>
                        </div>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Deseja prosseguir com a exclusão desse laboratório?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary btnExcluir">Sim</button>
                <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    <script>
        function ExibirModal(id) {
            $(".modal").modal();
            $(".btnExcluir").on('click', function () {
                $.ajax({
                    url: "/Laboratorios/Delete",
                    method: "POST",
                    data: { id: id },
                    success: function (data) {
                        $(".modal").modal('hide');
                        location.reload(true);
                    }
                });
            });
        }


        function ProjetorFiltro() {

            var ar = $('#myboolList').val().toLowerCase();
            console.log(ar);
            $.ajax({
                url: "Laboratorios/ProjetorPost",
                method: "POST",
                data: { Projetor: ar },
                success: function () {
                    location.reload(true);
                }
            });

        };
    </script>
}